[build]
  base = "ProgressiveWebAppProject/PWA/OpsmanagerApp"
  publish = "dist"
  command = "VITE_SUPABASE_URL=$SUPABASE_URL VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200