[build]
  base = "PWA/OpsmanagerApp"
  publish = "dist"
  command = "mkdir -p public && cp ../../src/favicon.svg public/favicon.svg && pnpm run build"

[context.deploy-preview]
  command = "mkdir -p public && cp ../../src/favicon.svg public/favicon.svg && pnpm run build"

[context.branch-deploy]
  command = "mkdir -p public && cp ../../src/favicon.svg public/favicon.svg && pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200