CREATE TABLE "states" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE "clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "RIF" VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE "clients_states" (
  "client_id" INTEGER NOT NULL,
  "state_id" INTEGER NOT NULL,
  PRIMARY KEY ("client_id", "state_id"),
  FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE,
  FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE CASCADE
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "client_id" INTEGER NOT NULL,
  "description" TEXT NOT NULL,
  "units_per_package" INTEGER NOT NULL CHECK ("units_per_package" > 0),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT
);

CREATE TABLE "reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "state_id" INTEGER NOT NULL,
  "client_id" INTEGER NOT NULL,
  "merchant_name" VARCHAR(255) NOT NULL,
  "salesman_name" VARCHAR(255) NOT NULL,
  "locality" TEXT NOT NULL,
  "establishment" TEXT NOT NULL,
  "date_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE RESTRICT,
  FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT
);

-- Consolidated inventory details table
CREATE TABLE "inventory_details" (
  "report_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "location_type" VARCHAR(20) NOT NULL CHECK ("location_type" IN ('salesfloor', 'stackroom')),
  "amount_per_unit" INTEGER NOT NULL DEFAULT 0 CHECK ("amount_per_unit" >= 0),
  "amount_per_package" INTEGER NOT NULL DEFAULT 0 CHECK ("amount_per_package" >= 0),
  PRIMARY KEY ("report_id", "product_id", "location_type"),
  FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE CASCADE,
  FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT
);